### PR TITLE
switch to dune

### PR DESCRIPTION
**Pull request by redianthus**
Hi Reuben,

I switched the project to dune. I had to fix a lot of trivial stuff. For some reasons tests are not working but I don't think it's related to my changes...

I got:

```sh
dune runtest
File "test/model_building.ml", line 103, characters 0-75:
Error: Expecting a singleton variable pattern!
make: *** [Makefile:26: tests] Error 1
```

Do you have any idea what's going on ?

Cheers.

### CODE REVIEW

**Comment by reubenrowe** [comment]
Hi Leo,

Thanks for submitting this.

Can you tell me which version of the compiler you are using?

Also, are you playing around with this for something in particular?

Reuben

**Comment by zapashcanon** [comment]
I'm using 4.07.1 ; if you can't reproduce, I can try with another version of the compiler.

I just wanted to read random code to get more familiar with ppx. I was curious about this one. :)

**Comment by reubenrowe** [comment]
Hi Leo,

There was a bug in the PPX rewriting code - I think I've fixed this in the commit I just pushed.

Please see what you think.

I'm not sure why this bug wasn't showing up in the original setup.

**Comment by zapashcanon** [comment]
Hi,

Indeed, it's working now. :)

I added something to `dune-project`, otherwise `dune build @all` would fail saying: `Error: Library js_of_ocaml-compiler not found`.

**Comment by reubenrowe** [comment]
Thanks Leo

**Pull request merged**
